name: Deploy
on:
  push:
    branches: [ main ]
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    # needs: debug
    steps:
      - uses: actions/checkout@v3
      - name: Buildah Build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ vars.QUAY_REPO }}/alpine
          tags: latest
          containerfiles: |
            ./Dockerfile
      - name: Push To quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ vars.QUAY_REPO }}/alpine
          tags: latest
          registry: ${{ vars.QUAY_REGISTRY }}
          username: ${{ vars.QUAY_REGISTRY_USER }}
          password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}


  trigger-python-build:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Dispatch python build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GLOBAL_GITHUB_ACCESS_TOKEN }}
          repository: net-sec/docker-python
          event-type: trigger-container-build


  trigger-dnssec-build:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Dispatch dnssec build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GLOBAL_GITHUB_ACCESS_TOKEN }}
          repository: net-sec/docker-dnssec
          event-type: trigger-container-build


  trigger-keepalived-build:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Dispatch keepalived build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          repository: net-sec/docker-keepalived
          event-type: trigger-container-build
